version: 3

tasks:
  ai:sonnet-4:
    desc: Run AI assistant
    cmds:
      - aider --model openrouter/anthropic/claude-sonnet-4

  ai:opus-4:
    desc: Run AI assistant
    cmds:
      - aider --model openrouter/anthropic/claude-opus-4

  ai:gemini:
    desc: Run AI assistant
    cmds:
      - aider --model gemini

  run:
    cmds:
      - go run cmd/main/main.go

  build:
    cmds:
      - go build -o ~/.bin/review cmd/main/main.go